@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package grondag.exotic_matter.varia.structures;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
import grondag.exotic_matter.varia.FieldsAreNonnullByDefault;